### ISSUE TITLE
Separate table for NYT winners

### ISSUE THREAD

**Issue by giratikanon** [newsdev/elex-loader#10]
Currently, NYT winner calls are part of the overrides table, which makes sense functionally. We may want to move it to a separate table, though, after New Hampshire. 

Other overrides, like candidate names and poll closing times, will migrate between staging and production, but NYT calls never should. Also, if they're in their own table, we don't have to worry about losing them if we have to re-import or modify an override table in an emergency.

**Comment by jeremyjbowers** [comment]
Yes, this is good.

Should pull `nyt_winner` and `nyt_called` out of the `race_overrides.sh` and `candidate_overrides.sh` and move them into their own `winner_overrides.sh` file.

**Comment by jeremyjbowers** [comment]
- [ ] Create `fields/override_winner.txt` containing the SQL command to create the table.
- [ ] Create `scripts/*/winner_overrides.sh` to load the create table command.
- [ ] Update `scripts/*/reload.sh` to add `winner_overrides.sh` to the reload command.
