### ISSUE TITLE
Script to generate a fake "zeros" file for racedates.

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/elex-loader#13]
Since the test data is identical WRT candidates and reporting units.

**Comment by giratikanon** [comment]
We should figure out a way to do this soon. Feels like most of the errors we're running into these days are related to AP's null initialization data, especially with so many primary dates to keep updated.

**Comment by jeremyjbowers** [comment]
AP has an api-level option for this. https://github.com/newsdev/elex/issues/227 Closing as a dupe.
