### ISSUE TITLE
Fix staging scripts and/or RDS users

### ISSUE THREAD

**Issue by giratikanon** [newsdev/elex-loader#15]
A few bugs with [scripts/stg/init.sh](https://github.com/newsdev/elex-loader/blob/master/scripts/stg/init.sh) on the new staging server: 
- The `elexadmin` user doesn't exist on staging (the superuser is `scotusadmin`)
- The `elex` user doesn't have permission to `createdb`:

```
createdb: database creation failed: ERROR:  permission denied to create database
```

**Comment by jeremyjbowers** [comment]
Fixed now; created an `elexadmin` user on staging and assigned the `rds_superuser` role to it.
