### ISSUE TITLE
Need to re-create view in elex_results during delegates.sh

### ISSUE THREAD

**Issue by giratikanon** [newsdev/elex-loader#17]
Including delegates in elex_results means that we need to re-create the view when we update delegate totals: 

```
elex-loader $ scripts/stg/delegates.sh 2016-02-20
STARTED: 22:16:46
------------------------------
NOTICE:  drop cascades to view elex_results
```

Otherwise, after delegates, elex_results does not exist.

**Comment by jeremyjbowers** [comment]
Oh, this was a good one.
