### ISSUE TITLE
reload.sh breaks elex-admin

### ISSUE THREAD

**Issue by giratikanon** [newsdev/elex-loader#18]
I think [reload.sh](https://github.com/newsdev/elex-loader/blob/master/scripts/stg/reload.sh) can break the elex-admin, because it reloads the database but doesn't populate the nyt_races for candidates. 

The admin doesn't display candidates, and can't mark candidates as NYT important, so no results appear on the frontend.

**Comment by jeremyjbowers** [comment]
Got this -- now sources the virtualenv and runs the `initialize_racedate.py` command.
