### ISSUE TITLE
Solve table drop conundrum

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/elex-loader#2]
Clients will read the DB and periodically see the table is empty / view doesn't exist.
`Unhandled rejection SequelizeDatabaseError: relation "elex_results" does not exist`
This happens because we are dropping the tables and bulk updating the records.

**Comment by jeremyjbowers** [comment]
This is a problem with any system where we have a synchronous process (the daemon loading results) and an asynchronous process (dynamic API calls). We can solve this by removing any dynamic requests to the API and bake JSON or HTML in the daemon loop since we'll know when the table is unavailable.

**Comment by jeremyjbowers** [comment]
Alternately can solve this with a cache. But caches are terrible and nobody has time for cache invalidation.

**Comment by jeremyjbowers** [comment]
Will talk to @wmandrews about this when he gets in.

**Comment by giratikanon** [comment]
Do we know how other people are handling this problem?

**Comment by jeremyjbowers** [comment]
Synchronous loading/baking cycles, in the case of NPR.

contact([{ "twitter": "@jeremybowers", "phone": "727-667-0510", "github": "
http://github.com/jeremyjbowers" }])
