### ISSUE TITLE
Include total delegates in results

### ISSUE THREAD

**Issue by wmandrews** [newsdev/elex-loader#22]
It would be great to include the total delegates and total superdelegates as candidate fields that can be added to the `elex_results` table. This will make it easier to make more advanced results views that include total delegates without making an extra AJAX request to the delegates API endpoint.

**Comment by giratikanon** [comment]
Looks like national delegate and superdelegate counts are in the delegates table as national rows, with `state` equal to `US`. I can add a field to `elex_results` that attaches those counts to each results row (or at least state rows).
