### ISSUE TITLE
Synchronize elex server time with real time

### ISSUE THREAD

**Issue by giratikanon** [newsdev/elex-loader#24]
Our Elex servers are about a minute or two off from real time. We should keep them synchronized.

**Comment by giratikanon** [comment]
I installed `ntp` to hopefully keep the servers synchronized, and also ran this manually on staging and production: 

```
ntpdate -s ntp.ubuntu.com
```

https://help.ubuntu.com/lts/serverguide/NTP.html

**Comment by wmandrews** [comment]
Do this on prd/stg-west.

**Comment by wmandrews** [comment]
Done.
