### ISSUE TITLE
Throw elex errors

### ISSUE THREAD

**Issue by giratikanon** [newsdev/elex-loader#4]
Currently, `elex-loader` fails with a cryptic message if environmental variables are missing or `elex` throws another error: 

```
ERROR:  missing data for column "unique_id"
CONTEXT:  COPY results, line 2: ""
```

Would be nice to pass through the `elex` error message.

**Comment by jeremyjbowers** [comment]
This is actually a problem with the underlying library elex uses to compile a command-line app -- it doesn't bubble up errors or logging. Eads and I were working through ways to solve this. I will revisit.
